export const ADD_NEW_PLAYER_REQUEST = "ADD_NEW_PLAYER_REQUEST";
export const ADD_NEW_PLAYER_REQUEST_SUCCESS = "ADD_NEW_PLAYER_REQUEST_SUCCESS";
export const ADD_NEW_PLAYER_REQUEST_FAILED = "ADD_NEW_PLAYER_REQUEST_FAILED";

export const CREATE_NEW_TEAM_REQUEST = "CREATE_NEW_TEAM_REQUEST";
export const CREATE_NEW_TEAM_REQUEST_SUCCESS =
  "CREATE_NEW_TEAM_REQUEST_SUCCESS";
export const CREATE_NEW_TEAM_REQUEST_FAILED = "CREATE_NEW_TEAM_REQUEST_FAILED";

export const SET_LOADING = "SET_LOADING";
